export const data = {
  dataPageTitle: "Best Make Up",
  dataTrophy:
    "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/Trophys/Best Make up.png",
  data: {
    BestCushion: {
      name:"Cushion",
      href:"/central-beuaty-award/BestMakeUp/BestCushion",
      first: {
        id: 1,
        name: "ESTEE LAUDER DOUBLE WEAR SOFT GLOW MATTE MAKEUP SPF 45/PA+++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "NARS NATURAL RADIANT LONGWEAR CUSHION FOUNDATION SPF 50/PA+++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "CLE DE PEAU BEAUTE RADIANT CUSHION FOUNDATION DEWY",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "M.A.C STUDIO FIX COMPACT SPF 50/PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/4.jpg",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "SULWHASOO PERFECTING CUSHION AIRY",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
    },
    BestEverydayLipstick: {
      name:"Every Day Lipstick",
      href:"/central-beuaty-award/BestMakeUp/BestEverydayLipstick",
      first: {
        id: 1,
        name: "CHANEL ROUGE ALLURE VELVET",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "YSL BEAUTY LOVESHINE LIPSTICK",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "TOM FORD SLIM LIP COLOR SHINE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "GUCCI GUCCI ROUGE À LÈVRES LIQUIDE MAT SOFT MATTE LIQUID LIPSTICK",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "CHARLOTTE TILBURY MATTE REVOLUTION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
    },
    BestFoundation: {
      name:"Foundation",
      href:"/central-beuaty-award/BestMakeUp/BestFoundation",
      first: {
        id: 1,
        name: "NARS LIGHT REFLECTING FOUNDATION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "ESTEE LAUDER DOUBLE WEAR STAY-IN-PLACE MAKEUP SPF10/PA++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "DIOR FOREVER SKIN GLOW",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "LANCÔME TEINT IDOLE ULTRA WEAR FOUNDATION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "SUQQU THE FOUNDATION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
    },
    BestLipMoisturizer: {
      name:"Lip Moisturizer",
      href:"/central-beuaty-award/BestMakeUp/BestLipMoisturizer",
      first: {
        id: 1,
        name: "DIOR ADDICT LIP GLOW",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "Lip Moisturizers 2024 HERMÈS Rouge Hermès, Lip care balm",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "BOBBI BROWN EXTRA PLUMP LIP SERUM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CHANEL ROUGE COCO BAUME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "TOM FORD SOLEIL SUMMER LIQUID LIP BLUSH",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
    },
    BestMakeupBase: {
      name:"Makeup Base",
      href:"/central-beuaty-award/BestMakeUp/BestMakeupBase",
      first: {
        id: 1,
        name: "BOBBI BROWN VITAMIN ENRICHED FACE BASE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "HOURGLASS Veil Mineral Primer-SPF 15",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "JUNG SAEM MOOL Masterclass Glow Base",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "shu uemura unlimited block booster primer",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "KANEBO EVEN FIT PRIMER",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBase/qr1.png",
        link: "",
      },
    },
    BestPowder: {
      name:"Powder",
      href:"/central-beuaty-award/BestMakeUp/BestPowder",
      first: {
        id: 1,
        name: "GUERLAIN MET 24 PEARL/PDR 2 ROSE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "NARS LIGHT REFLECTING SETTING POWDER",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "M.A.C STUDIO FIX POWDER PLUS FOUNDATION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CHANEL POUDRE UNIVERSELLE LIBRE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "HOURGLASS VANISH AIRBRUSH PRESSED POWDER",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
    },
  },
};
