export const data = {
  dataPageTitle: "Best Skincare",
  dataTrophy:
    "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/Trophys/SkinCare.png",
  data: {
    BestCushion: {
      name:"Cushion",
      href:"/central-beuaty-award/BestMakeUp/BestCushion",
      first: {
        id: 1,
        name: "DIOR PRESTIGE LA MICRO-LOTION DE ROSE ADVANCED",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "LA MER THE TREATMENT LOTION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "SHISEIDO EUDERMINE Activating Essence",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "IPSA ESSENCE LOTION ULTIMATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/4.jpg",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "LANCÔME CLARIFIQUE DOUBLE TREATMENT ESSENCE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestCushion/qr1.png",
        link: "",
      },
    },
    BestEverydayLipstick: {
      name:"Every Day Lipstick",
      href:"/central-beuaty-award/BestMakeUp/BestEverydayLipstick",
      first: {
        id: 1,
        name: "ESTEE LAUDER ADVANCED NIGHT REPAIR EYE SUPERCHARGED GEL-CREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "CLARINS DOUBLE SERUM EYE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "LA MER THE EYE CONCENTRATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CLE DE PEAU BEAUTE EYE CONTOUR CREAM SUPREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "LA PRAIRIE SKIN CAVIAR LUXE EYE CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestEverydayLipstick/qr1.png",
        link: "",
      },
    },
    BestFoundation: {
      name:"Foundation",
      href:"/central-beuaty-award/BestMakeUp/BestFoundation",
      first: {
        id: 1,
        name: "SHISEIDO MEN Ultimune Power Infusing Concentrate",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "IPSA THE TIME RESET AQUA",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/2.jpg",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "SK-II MEN FACIAL TREATMENT ESSENCE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/3.jpg",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CLINIQUE CLINIQUE FOR MEN FACE WASH",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "KIEHL'S AGE DEFENDER CREAM MOISTURIZER",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestFoundation/qr1.png",
        link: "",
      },
    },
    BestLipMoisturizer: {
      name:"Lip Moisturizer",
      href:"/central-beuaty-award/BestMakeUp/BestMoisturizer",
      first: {
        id: 1,
        name: "SHISEIDO VITAL PERFECTION Uplifting and Firming Advanced Cream",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "DIOR PRESTIGE LA CRÈME TEXTURE FINE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "ESTEE LAUDER REVITALIZING SUPREME+ NIGHT POWER BOUNCE CREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "LA MER THE MOISTURIZING SOFT CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "AUGUSTINUS BADER THE CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestLipMoisturizer/qr1.png",
        link: "",
      },
    },
    BestMakeupBeauty: {
      name:"Makeup Beauty",
      href:"/central-beuaty-award/BestMakeUp/BestMakeupBeauty",
      first: {
        id: 1,
        name: "LA MER THE CONCENTRATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "CLARINS DOUBLE SERUM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "ESTEE LAUDER ADVANCED NIGHT REPAIR SYNCHRONIZED MULTI RECOVERY COMPLEX SERUM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "DIOR PRESTIGE LA MICRO HUILE DE ROSE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "SK-II GenOptics Ultraura Essence",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestMakeupBeauty/qr1.png",
        link: "",
      },
    },
    BestPowder: {
      name:"Powder",
      href:"/central-beuaty-award/BestMakeUp/BestPowder",
      first: {
        id: 1,
        name: "CLARINS UV PLUS [3P] ANTI-POLLUTION SPF50 PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "ELIXIR DAY CARE REVOLUTION SPF50+ PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "SHISEIDO URBAN ENVIRONMENT TRIPLE BEAUTY SUNCARE EMULSION SPF 50+ PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "DECORTE SUN SHELTER MULTI PROTECTION TONE UP CC 01 SPF50+/PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "KIEHL'S ULTRA LIGHT DAILY UV DEFENSE AQUA GEL SPF 50 PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestMakeUp/BestPowder/qr1.png",
        link: "",
      },
    },
  },
};
