export const data = {
  dataPageTitle: "Best Skincare",
  dataTrophy:
    "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/Trophys/SkinCare.png",
  data: {
    BestEssence: {
      name:"Essence",
      href:"/central-beuaty-award/BestSkincare/BestEssence",
      first: {
        id: 1,
        name: "DIOR PRESTIGE LA MICRO-LOTION DE ROSE ADVANCED",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "LA MER THE TREATMENT LOTION",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "SHISEIDO EUDERMINE Activating Essence",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "IPSA ESSENCE LOTION ULTIMATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "LANCÔME CLARIFIQUE DOUBLE TREATMENT ESSENCE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEssence/qr5.png",
        link: "",
      },
    },
    BestEyeCream: {
      name:"Eye Cream",
      href:"/central-beuaty-award/BestSkincare/BestEyeCream",
      first: {
        id: 1,
        name: "ESTEE LAUDER ADVANCED NIGHT REPAIR EYE SUPERCHARGED GEL-CREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "CLARINS DOUBLE SERUM EYE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "LA MER THE EYE CONCENTRATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CLE DE PEAU BEAUTE EYE CONTOUR CREAM SUPREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "LA PRAIRIE SKIN CAVIAR LUXE EYE CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestEyeCream/qr5.png",
        link: "",
      },
    },
    BestMenSkincare: {
      name:"Men's Skincare",
      href:"/central-beuaty-award/BestSkincare/BestMenSkincare",
      first: {
        id: 1,
        name: "SHISEIDO MEN Ultimune Power Infusing Concentrate",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "IPSA THE TIME RESET AQUA",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "SK-II MEN FACIAL TREATMENT ESSENCE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "CLINIQUE CLINIQUE FOR MEN FACE WASH",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "KIEHL'S AGE DEFENDER CREAM MOISTURIZER",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMenSkincare/qr5.png",
        link: "",
      },
    },
    BestMoisturizer: {
      name:"Moisturizer",
      href:"/central-beuaty-award/BestSkincare/BestMoisturizer",
      first: {
        id: 1,
        name: "SHISEIDO VITAL PERFECTION Uplifting and Firming Advanced Cream",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/1.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "DIOR PRESTIGE LA CRÈME TEXTURE FINE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/2.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/qr1.png",
        link: "",
      },
      third: {
        id: 3,
        name: "ESTEE LAUDER REVITALIZING SUPREME+ NIGHT POWER BOUNCE CREME",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/3.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/qr1.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "LA MER THE MOISTURIZING SOFT CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/4.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/qr1.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "AUGUSTINUS BADER THE CREAM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/5.png",
        imageQr: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestMoisturizer/qr1.png",
        link: "",
      },
    },
    BestSerum: {
      name:"Serum",
      href:"/central-beuaty-award/BestSkincare/BestSerum",
      first: {
        id: 1,
        name: "LA MER THE CONCENTRATE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSerum/1.png",
        imageQr: "",
        link: "",
      },
      second: {
        id: 2,
        name: "CLARINS DOUBLE SERUM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSerum/2.png",
        imageQr: "",
        link: "",
      },
      third: {
        id: 3,
        name: "ESTEE LAUDER ADVANCED NIGHT REPAIR SYNCHRONIZED MULTI RECOVERY COMPLEX SERUM",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSerum/3.png",
        imageQr: "",
        link: "",
      },
      fourth: {
        id: 4,
        name: "DIOR PRESTIGE LA MICRO HUILE DE ROSE",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSerum/4.png",
        imageQr: "",
        link: "",
      },
      fifth: {
        id: 5,
        name: "SK-II GenOptics Ultraura Essence",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSerum/5.png",
        imageQr: "",
        link: "",
      },
    },
    BestSuncreen: {
      name:"Suncreen",
      href:"/central-beuaty-award/BestSkincare/BestSuncreen",
      first: {
        id: 1,
        name: "CLARINS UV PLUS [3P] ANTI-POLLUTION SPF50 PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSuncreen/1.png",
        imageQr: "",
        link: "",
      },
      second: {
        id: 2,
        name: "ELIXIR DAY CARE REVOLUTION SPF50+ PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSuncreen/2.png",
        imageQr: "",
        link: "",
      },
      third: {
        id: 3,
        name: "SHISEIDO URBAN ENVIRONMENT TRIPLE BEAUTY SUNCARE EMULSION SPF 50+ PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSuncreen/3.png",
        imageQr: "",
        link: "",
      },
      fourth: {
        id: 4,
        name: "DECORTE SUN SHELTER MULTI PROTECTION TONE UP CC 01 SPF50+/PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSuncreen/4.png",
        imageQr: "",
        link: "",
      },
      fifth: {
        id: 5,
        name: "KIEHL'S ULTRA LIGHT DAILY UV DEFENSE AQUA GEL SPF 50 PA++++",
        image: "/MICROSITES_CREaiVE/img/CentralBauetyAward2024/BestSkincare/BestSuncreen/5.png",
        imageQr: "",
        link: "",
      },
    },
  },
};
