
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <audio src="/MICROSITES_CREaiVE/mp3/award.mp3" autoPlay />
      <body className={inter.className}>{children}</body>
      <div className="absolute flex z-50 w-full m-auto top-[97%] items-center justify-center">
        <img src="/MICROSITES_CREaiVE/img/CentralBauetyAward2024/PoweredBy.png" className="w-[100px] mr-10" />
      </div>
    </html>
  );
}
