export const data = {
  dataPageTitle: "Fragrance",
  dataTrophy:
    "/img/CentralBeautyAward2024/Trophys/Best Fragrance.png",
  data: {
    BestFragranceEveryday: {
      name:"Frangrance Everyday",
      href:"/central-beuaty-award/BestFrangrance/BestFragranceEveryday",
      first: {
        id: 1,
        name: "DIOR MISS DIOR BLOOMING BOUQUET",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/1.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "JO MALONE LONDON English Pear & Sweet Pea Cologne",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/2.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "CHANEL CHANCE EAU TENDRE EAU DE PARFUM",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/3.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "LANCÔME IDOLE EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/4.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "GUCCI FLORA GORGEOUS GARDENIA EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/5.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceEveryday/qr5.png",
        link: "",
      },
    },
    BestFragranceSporty: {
      name:"Fragrance Sporty",
      href:"/central-beuaty-award/BestFrangrance/BestFragranceSporty",
      first: {
        id: 1,
        name: "CHANEL BLEU DE CHANEL EAU DE PARFUM SPRAY",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/1.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "DIOR SAUVAGE EAU DE TOILETTE",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/2.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "VERSACE EROS EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/3.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "JO MALONE LONDON CYPRESS & GRAPEVINE COLOGNE INTENSE",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/4.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "YSL BEAUTY Y MEN EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/5.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSporty/qr5.png",
        link: "",
      },
    },
    BestFragranceSpecialOccasion: {
      name:"Fragrance Special Occasion",
      href:"/central-beuaty-award/BestFrangrance/BestFragranceSpecialOccasion",
      first: {
        id: 1,
        name: "NARCISO RODRIGUEZ ALL OF ME EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/1.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/qr1.png",
        link: "",
      },
      second: {
        id: 2,
        name: "DIPTYQUE ORPHEON EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/2.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/qr2.png",
        link: "",
      },
      third: {
        id: 3,
        name: "GIORGIO ARMANI ARMANI PRIVE THE YULONG EDT",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/3.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/qr3.png",
        link: "",
      },
      fourth: {
        id: 4,
        name: "Occasional Fragrances 2024 HERMÈS Hermessence Oud Alezan Eau De Parfum",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/4.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/qr4.png",
        link: "",
      },
      fifth: {
        id: 5,
        name: "PRADA PARADOXE INTENSE EDP",
        image: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/5.png",
        imageQr: "/img/CentralBeautyAward2024/BestFrangrance/BestFragranceSpecialOccasion/qr5.png",
        link: "",
      },
    },
  },
};
